### ISSUE TITLE
REQUEST - support user defined functions

### ISSUE THREAD

**Issue by maded2** [Knetic/govaluate#25]
hi,   this library is great.  User defined parameters/variables is very welcome.  Is there any chance you can add user defined functions as well (ideally nested user defined functions).

example:

"(requests_made("5m") * requests_succeeded("5m") / 100) >= 90"

**Comment by vjeantet** [comment]
That could be a killer feature, I like that !

**Comment by Knetic** [comment]
Thanks for using the library! I've thought about adding support for this before, but never did it because I generally found that any function I could want to call could just as easily be called before the expression was evaluated, with the result passed as a parameter. 

However, I know that may not be feasible for some advanced use cases, and your example of something that aggregates data within the expression was pretty compelling. Also, like three people all voted for this at once (which I think makes this the most popular issue on the project :stuck_out_tongue: ), so I sat down and implemented it as of db7388bbf6d55eff15418bdc90cfacf05c79f7db .

**Comment by maded2** [comment]
thanks for the quick turnaround, will try out very soon.  Does it support nested user-defined function?

**Comment by Knetic** [comment]
There's some explanation on usage in the readme - but yes, it does. You can give a function any number of arguments, and include any other operations you like. For example; the following expression is perfectly valid and will work like expected (assuming the proper function/parameters are passed in):

```go
    // returns the largest of the three parameters. The middle gets the absolute value of 'anotherValue'
    "max(someValue, abs(anotherValue), 10 * lastValue)"
```

**Comment by maded2** [comment]
this is great, many thanks.

**Comment by emirigoyen** [comment]
Good day ....
Query: Is there a mechanism to nest user-defined functions dynamically? That is, to build compound functions defined by the user, type f (g (h (x + 4)))? with f, g and h user-defined functions dynamically?
