### ISSUE TITLE
Support for arrays

### ISSUE THREAD

**Issue by mirdhyn** [Knetic/govaluate#26]
Hi,
Would it be possible to add array support (i.e. `IN` and `NOT IN`), please?

I know that you closed PR #9, but I would like to have a follow-up with that :)

This is needed to be able to parse logstash expressions, and for that, we need to be able to check if a value is present (or not) in an array.

The most common use-case is that filters are adding tags on failure and send these failed message to a specific output.

For example:
```
if "_dateparsefailure" in [tags] {
   stdout { codec => rubydebug }
}
```

**Comment by Knetic** [comment]
The main reason I rejected it originally was because the PR had support that I didn't really think was complete enough to bring into mainline (no array literal syntax, mainly). I was also a little skeptical about how necessary arrays were, since the only operator that seems to apply to them was the `IN` operator, which overall I wasn't sure was valuable. _But_, that said, I've since found myself wishing I had the `IN` operator just to make a series of `==` statements into one statement :P

I'm open to implement the `IN` operator, and array literals are actually already implemented (as a side-effect of the request in #25 ), but I really don't want to support a `NOT IN` operator, I would prefer to only use the unary `!` to indicate inversion (similar to how JS does it). Would those changes fit your use cases?

**Comment by Knetic** [comment]
Also, glancing over [Logstash expressions](https://www.elastic.co/guide/en/logstash/current/event-dependent-configuration.html#conditionals), it occurs to me that this seems really similar to the `EvaluableExpression.ToSQLQuery()` function that exists right now. 

Are you parsing logstash expressions _into_ EvaluableExpression, or creating them _from_ EvaluableExpressions? If you're building Logstash expressions _from_ this library, I think that having a `ToLogstashExpression()` function (similar to `ToSQLQuery()`) would actually suit your purposes pretty well, since then you could fairly easily translate things like the `&&` and `||` operators into the textual `AND` / `OR` without needing this library to directly them (very similar to how the SQL implementation does it).

**Comment by mirdhyn** [comment]
Unfortunately, I need to parse logstash expression, not generate them, but thank you :)

Having `IN` but not `NOT IN` would be acceptable for me.
I believe I could do some pre-processing to convert expressions with `NOT IN` into  `!` and `IN`.

**Comment by Knetic** [comment]
Done as of 62c57ed0d37e614bc31cdb0bc7dc62edfa476368
