### ISSUE TITLE
String Compare

### ISSUE THREAD

**Issue by snadrus** [Knetic/govaluate#29]
"abc" < "ad"
Evaluates to True in GoLang. 
Please add string compare as I need it for a project I'm open-sourcing soon.

**Comment by Knetic** [comment]
I was a little hesitant to do this, since I've never used lexicographical ordering like this. And since there are so many ways to lexicographically order, it seemed better suited to users writing functions to fit the needs they have. 
But it looks like Python, Ruby, Nim, (Go, of course), Mongo, SQL, and many others all support this operation using their normal comparator operators; so it's more common than I thought.

I'll probably have time to implement this during the coming week. Will update once it's up.

**Comment by Knetic** [comment]
Added as of 188c506adbcda72cfa0ad361291617bf793ccbf3 .
