### ISSUE TITLE
Multiple panics (and a torture-tool)

### ISSUE THREAD

**Issue by abrander** [Knetic/govaluate#47]
First of all; thanks for govaluate. It's awesome! :)

I have written a small torture test for hunting panics:
https://gist.github.com/abrander/fa05ae9b181b48ffe7afb12c961b6e90

The tool does 100,000,000 evaluations in about 10 minutes on my workstation.

I'm not familiar enough with govaluate to fix these panics myself, but maybe someone else could have a look?

#46 fixes many cases.

**Comment by Knetic** [comment]
Thanks! And thanks for taking the time to write the tool! I'd looked into fuzzers for testing a while back, but never actually put anything meaningful together - but this is fantastic. Even just running for a couple minutes it's found tens of thousands of panic cases.

I'll probably integrate this into the automated tests at some point after seeing how many of these panics I can get rid of.

**Comment by Knetic** [comment]
That torture tool is really fantastic. I put it into the test suite (but defaults to skipped, so that only Travisci does it) and fixed the three bugs which seemed to lead to panics. Everything passes now. I'm aiming to do more followup work later, but for now at least all the known cases work.

Thanks again! Closing this since I couldn't find any more panics with the tool.

**Comment by abrander** [comment]
Wow man, you're fast! Thanks for fixing.

I'm glad you find the tool useful, but I'm not sure how happy Travis is if you're hammering for minutes ;-)
