### ISSUE TITLE
Undefined function

### ISSUE THREAD

**Issue by Xfennec** [Knetic/govaluate#50]
Re,

When creating a new expression with `NewEvaluableExpressionWithFunctions`, I get a "strange" error message if it contains a call to an undefined function: `Cannot transition token types from VARIABLE [foobar] to CLAUSE [40]` (the expression here was simply `foobar()`, which is not defined).

I'm afraid my end users won't understand this message properly. Is it possible to return something like "undefined function foobar"? Or build the expression anyway (like for undefined parameters) so it let me check FUNCTION tokens before calling `Evaluate`?

Thanks!

**Comment by Knetic** [comment]
It's a bit tricky. The library only decides a token is a FUNCTION if it finds an unquoted string that matches a key in the functions map - it doesn't look ahead to see the parenthesis. So if there's no function given that matches the string, it assumes it's a VARIABLE. It does this because functions are given at parse-time and don't change (it doesn't keep a reference to the map or anything).

I can definitely see a good case for having a specific error message for that case (VARIABLE to CLAUSE grammar), because of how common it might be to typo function names (or assume a function is available that actually isn't).

I'll put together a change for this soon.

**Comment by Xfennec** [comment]
Nice, thanks.

**Comment by Knetic** [comment]
Done as of https://github.com/Knetic/govaluate/commit/34df01f34403371daab5d0ac8a0cd2a4c4deb6fe
