### ISSUE TITLE
Only the last object is valid when using class methods as functions.

### ISSUE THREAD

**Issue by hsluoyz** [Knetic/govaluate#54]
I want to use a class method like below in the functions.

```golang
func (c *MyClass) method(arg1 int, arg2 int) bool {

}

functions["func1"] = func(args ...interface{}) (interface{}, error) {
	arg1:= args[0].(string)
	arg2:= args[1].(string)
	return (bool)(obj1.method(arg1, arg2)), nil
}
functions["func2"] = func(args ...interface{}) (interface{}, error) {
	arg1:= args[0].(string)
	arg2:= args[1].(string)
	return (bool)(obj2.method(arg1, arg2)), nil
}

```

``obj1`` and ``obj2`` are two different instances of ``MyClass``.

After some debugging, I found that ``func1`` is not working, because it's actually calling ``obj2.method`` instead of ``obj1.method``. So it seems that the object itself for a class method is not regarded as a parameter.

Maybe a workaround is that defining a global function and explicitly regarding the class object a parameter of this function. But it requires to modify the expression to add the class object into parameters, which is kind of ugly.

So I want to ask is there any better way to let class methods work well during the expression evaluation? Thanks.

**Comment by Knetic** [comment]
What you're doing ought to work just fine, I'm not sure what the problem is. I [added a test](https://github.com/Knetic/govaluate/commit/f9425c56a9ecf49894201eeacda18212b4d235dc) to try to replicate it, but it seems to work for me. It works a little differently than the example you gave above (works with numeric values instead of strings), but seems like it ought to exhibit the behavior - but this test passes.

Could you put together a test that shows the behavior you're seeing?

**Comment by hsluoyz** [comment]
The above example of obj1 and obj2 is not revealing my problem. Please try the below example:

```golang
type TestClass struct {
	level    int
}

func newTestClass(level int) *TestClass {
	rm := TestClass{}
	rm.level = level
	return &rm
}

func (rm *TestClass) getLevel() int {
	return rm.level
}

func TestTestClass1(t *testing.T) {
	rm1 := newTestClass(1)
	rm2 := newTestClass(2)

	functions := map[string]govaluate.ExpressionFunction {
		"func1": func(args ...interface{}) (interface{}, error) {
			return (float64)(rm1.getLevel()), nil
		},
		"func2": func(args ...interface{}) (interface{}, error) {
			return (float64)(rm2.getLevel()), nil
		},
	}

	expString := "func1() + func2()"
	expression, _ := govaluate.NewEvaluableExpressionWithFunctions(expString, functions)

	result, _ := expression.Evaluate(nil)
	fmt.Print(result)
}

func TestTestClass2(t *testing.T) {
	rms := make(map[string]*TestClass)
	rms["func1"] = newTestClass(1)
	rms["func2"] = newTestClass(2)

	functions := make(map[string]govaluate.ExpressionFunction)

	for key := range rms {
		functions[key] = func(args ...interface{}) (interface{}, error) {
			return (float64)(rms[key].getLevel()), nil
		}
	}

	expString := "func1() + func2()"
	expression, _ := govaluate.NewEvaluableExpressionWithFunctions(expString, functions)

	result, _ := expression.Evaluate(nil)
	fmt.Print(result)
}
```

``TestTestClass1`` result is 3, but ``TestTestClass2`` result is 4. My actual scenario is like 4, all functions are stored in a map and assigned to ``functions`` using a for loop. But it seems that the evaluation doesn't recognize the for loop assignment very well. So in ``TestTestClass2``, both func1() and func2() return 2, and add up to 4. My functions are dynamic and I have to store them in a data structure like a map. Any solutions?

**Comment by Knetic** [comment]
Ah, I recognize the problem. It has to do with closures, not govaluate. This is the problem code:

```go
for key := range rms {
		functions[key] = func(args ...interface{}) (interface{}, error) {
			return (float64)(rms[key].getLevel()), nil
		}
	}
```
There is only one variable named `key`. Every iteration, the value of `key` changes. But every function you've created will point to the current value of `key` when it is _called_, not when the function is _defined_. So all your functions end up referencing the same `key` variable, thus all return the same value.

You can fix this by wrapping your function declaration so that a _copy_ of `key` is given to each function (probably what you were expecting anyway), like so:

```go
func wrapLevel(value *TestClass) govaluate.ExpressionFunction {
    return func(args ...interface{}) (interface{}, error) {
        return (float64)(value.getLevel()), nil
    }
}

// ... in your loop
for key := range rms {
    functions[key] = wrapLevel(rms[key])
}
```

**Comment by hsluoyz** [comment]
This is the issue. In fact, I found the fix can be simpler. Thanks for the help!

```golang
for key := range rms {
		rm := rms[key]
		functions[key] = func(args ...interface{}) (interface{}, error) {
			return (float64)(rm.getLevel()), nil
		}
	}
```
