### ISSUE TITLE
Can I use a struct method (or have an object pointer as the parameter) in functions?

### ISSUE THREAD

**Issue by hsluoyz** [Knetic/govaluate#56]
Hi, I have a struct like ``testUser`` as below.

```golang
type testUser struct {
	name string
	domain string
}

func newTestUser(name string, domain string) *testUser {
	u := testUser{}
	u.name = name
	u.domain = domain
	return &u
}

func (u *testUser) getAttribute(attributeName string) string {
	ru := reflect.ValueOf(u)
	f := reflect.Indirect(ru).FieldByName(attributeName)
	return f.String()
}

func getAttribute2(u *testUser, attributeName string) string {
	ru := reflect.ValueOf(u)
	f := reflect.Indirect(ru).FieldByName(attributeName)
	return f.String()
}

func getAttribute3(userName string, attributeName string) string {
	u := getUserObjectByName(userName) // for example using a map
	ru := reflect.ValueOf(u)
	f := reflect.Indirect(ru).FieldByName(attributeName)
	return f.String()
}

alice := newTestUser("alice", "domain1")
```

I'd like to make the properties of testUser object dynamically parsed in govaluate, the object is an input parameter. I don't know if this is possible.

1. The best expectation is: expression = ``alice.name``, and use ``alice`` object as a parameter. If this is not possible:
2. I define a ``func (u *testUser) getAttribute(attributeName string) string`` function as above. expression = ``alice.getAttribute("name")``, and use ``alice`` object as a parameter. If this is either not possible:
3. I define a global ``func getAttribute2(u *testUser, attributeName string) string`` function as above. expression = ``getAttribute2(alice, "name")``, and use ``alice`` object as a parameter.
4. The last way to to define ``func getAttribute3(userName string, attributeName string) string``. expression = ``getAttribute2("alice", "name")``, and use ``alice`` name as a string parameter. I know this way works. But it is inconvenient because I need to implement a get-object-by-name function via a map. So I don't want this way.

So my priority is: 1. > 2. > 3. > 4. Do any of the above ideas 1, 2, 3 work in govaluate? Thanks!

**Comment by Knetic** [comment]
I agree it makes sense to allow calling methods on passed-in structs, and that it makes sense to relax the restriction on having struct params. I'd expect **1** is the best approach, since it acts like other languages and flows pretty naturally. The syntax of it make it easier to parse as well. It also means that users won't need to write extra code to call those methods (like would need to happen with **2** and **3**). However I haven't actually tried doing it yet. I'll give it a shot soon though!

There are probably implications around reflection and whether or not a struct exports the method.

**Comment by lukehumphreys** [comment]
Hey I'm interested in this functionality too, this is the only thing that's stopping my team from using govaluate. Can you let me know if you have made any progress on this? If not we would be keen to contribute if you could point us in the right direction.
Thanks

**Comment by Knetic** [comment]
I just started working on it. There were a number of ways to approach it, and while most ways would 'work' I haven't been sure what would be the best, so i didn't want to advise on how to implement it before I knew myself. There's a lot of little details and gotchas. I think I've got the right approach lined up though.

These are the assumptions i'm operating under, but as a sort of "Request For Comments", let me know if any of these don't make sense (since this thread has the people interested in the functionality):

* Unexported fields/methods will not be usable 
(even though `reflect` totally lets you do it, it seems like this would lead people to using expressions to shortcut the public api of the objects they're using)
* Any fields accessed in this way will go through all the same type checking and conversation as a regular parameter
(so any `int` turns to `float64`, etc)
* No void methods can be called
(it doesn't make sense in the context of an expression - every stage needs to return some value, so that ultimately a call to `Evaluate` brings back one value)
* If two values are returned from a parameter method call, the first is treated as the "value" and the second as an `error`. 
* More than two return values results in an error. 
* If the second return value is not of type `error`, this also results in an error.
* Pointers to structs are not accepted
(it's long been an unwritten rule that expressions do not have side effects on the parameters they're given, I think that's a good standard)

If any of those seem iffy for your use cases, let me know soon. I think they're general enough to work, it's what I'd expect from using it, but I don't want to overlook any use cases.

**Comment by hsluoyz** [comment]
Hi @Knetic ,

I think the assumptions are very reasonable. It will meet my need at least.

My only concern is, why doesn't govaluate support ``int`` type? In fact, ``int`` is the most often used data type. I think the ``(float64)`` conversion is not good-looking and can be error-prone. In fact I made such mistakes at the first time I use govaluate. I just can't get the correct evaluation result when calculating integer numbers.

If you insist not to support ``int``, maybe you can still use float64 in the internal side of govaluate, but help do the conversion from ``int`` to ``float64`` if the user passes in integers? Thanks.

In fact, this is far from this issue, and I can propose another issue if you want:)

**Comment by cmars** [comment]
I'd like to use govaluate for glop, which executes declarative statechart-like models (for example, [pingpong.yaml](https://github.com/cmars/glop/blob/the-harelian-rewrite/pingpong.yaml)). govaluate is working pretty well for simple expressions in my asserts and conditionals, but I need to also evaluate nested field lookups through structs and maps -- structured messages are essential. I don't have a strong use case for method calls in expressions though.

My feedback on the assumptions above:

> Unexported fields/methods will not be usable
(even though reflect totally lets you do it, it seems like this would lead people to using expressions to shortcut the public api of the objects they're using)

+1. Nice-to-have would be struct tags that let you customize the field names in the expression evaluation. Tags could also be useful to hide some fields from expressions.

> Any fields accessed in this way will go through all the same type checking and conversation as a regular parameter
(so any int turns to float64, etc)

+1

> Pointers to structs are not accepted
(it's long been an unwritten rule that expressions do not have side effects on the parameters they're given, I think that's a good standard)

I don't think you'll be able to prevent side-effects in method calls. Wrap a pointer with a struct, and that pointer gets copied with the struct; pass-by-value method targets can still cause side-effects via that pointer.

If you only support field lookups (and key lookups in maps) then pointer or value doesn't matter, and there's sure to be no side effects. Callers can always define entity structs that represent the contents of the data to expose in expressions.

I assume an error would result from dereferencing null/missing keys.

**Comment by Knetic** [comment]
@hsluoyz the main reason for converting all numbers into `float64` was for simplicity - all numeric operators can assume that they are operating on `float64`, and there's no typechecking or reflection required to get any given variable to a state where it can be added, subtracted, bitshifted, compared, or otherwise used. `float64` also fits rather a lot of use cases, and there's not many cases where integers do something that floats cannot. In the cases where people want integers, they generally tend to want very large ones (such as #51 ) for things like financial or highly-precise scientific calculations. But libraries which achieve those kinds of bigdecimal or biginteger goals tend to be _extremely_ slow and wasteful, which goes against one of the guiding principles of this library - speed.  The library is not _aggressively_ optimized for speed, but it is designed to be quite fast compared to others in its class (though I haven't done much formal benchmarking), and open to further optimizations without changing the overall design.

I'm mulling over a "PreciseExpression" (or something like that) which would be like "EvaluableExpression", but which instead would use some form of bigdecimal for all numeric operations (suitable for scientific and financial applications) - but i haven't even begun to prototype such a thing.

**Comment by Knetic** [comment]
@cmars All good points. I'll strikethrough the "pointers to structs" requirement, since it now occurs to me that people could pass anonymous functions that modify parameters to `NewEvaluableExpressionWithFunctions` today and have a similar effect, so the "no side-effects" thing is already more guideline than rule.

I expect to push a working version of all this quite soon, although perhaps not immediately with maps/structtag support. @lukehumphreys I know it's been a month since this feature was brought up, but in the off chance your team hasn't yet found/made an alternative - are there any other requirements besides the ones listed above you'd like to see listed out, before the design becomes official?

**Comment by Knetic** [comment]
Alright, this is all implemented as of https://github.com/Knetic/govaluate/commit/9b61aab0160cbe2f41a04934e2257332b8b6bf5f . No maps or struct tags yet, though i expect to get to those at some point soon. The path is also a lot clearer for how to add support for maps/tags if others would like to add support right away (the commits since https://github.com/Knetic/govaluate/commit/f9296ab15009320547a78ceb4e841c80daf2719d show the process used to add support for this).

It's in master branch and everything looks good, but i'll wait until some people have used it and can confirm it does what they wanted.

**Comment by hsluoyz** [comment]
Hi @Knetic ,

The new accessor feature indeed works! I have successfully used it in my project:) I have two questions here.

1. When I use a pointer of a struct rather than the struct itself, govaluate reports error:

```
panic: Unable to access 'Owner', 'r_obj' is not a struct
```

It seems that govaluate checks the type of the argument is Ptr rather than Struct, but I think there's no much difference. Can govaluate recognize the struct pointer too besides the struct itself?

2. Although you explained about it above, but I still want to ask if it's possible to support private members in a struct? My software is not for end-users and my users are also developers, I can't guarantee that they will always use this feature for public members. And the error message is not clear for this wrong usage. If this ban is for security reason, I don't think it works as we wish, because the function feature already allows the user to call arbitrary function in govaluate. So there's no much gain to ban private members in struct. What do you say?

Thanks again for the great work!

**Comment by Knetic** [comment]
Hey @hsluoyz , thanks! And sorry for the delay on getting back to you. I had actually meant to support pointers with the implementation pushed two weeks ago, but i hadn't added any tests to make sure that they worked - and so the behavior you're seeing is actually a bug. I had initially thought pointers would be a bad idea, but you and cmars both brought up good points. I've pushed https://github.com/Knetic/govaluate/commit/31678da578da40773346157387ef9933d650eb23 , which ought to support pointers-to-structs.

As for private members, I still don't think it's a good idea :[ while your users may be internal, I can't guarantee that all users of the library will be - one of the main use cases for the library is for external users to specify queries or formulas that a service can evaluate for them. 
I'm extremely wary of having too much `Eval`-like capabilities (given how difficult it is to be secure). It's possible to call struct public methods now, and yes it's possible that those could have unwanted side effects. But calling any function from the library requires that the developer be very specific about what they want to allow - they need to specifically define every parameter passed in, and every static function available. It's meant to make the developer very aware of what they're allowing users to do.
There's really no way to add any metadata to functions (such as struct tags), so there's not an easy way to determine what struct methods should be available to the expression and which shouldn't be - except to check if they're exported or not.

Is it possible for your team to just make the functions you want to use exported?

**Comment by hsluoyz** [comment]
First thanks for the fix of pointers!

I can't export the functions by myself, because my project is also a library and it's my user's decision whether to export them. I think the current solution is already enough good for my usage:) I will find you when there're any further issues from myself or my users.
