### ISSUE TITLE
Passing date values in parameters

### ISSUE THREAD

**Issue by VijayBhore** [Knetic/govaluate#62]
First of all, thank you so much for your library. It is awesome.

I am trying to evaluate an expression with a date value set in parameters. I have posted a question on StackOverflow about this: https://stackoverflow.com/questions/44893202/compare-date-values-in-expression-using-govaluate

Is there a way i can achieve the following:

```
package main

import (
    "github.com/Knetic/govaluate"
    "fmt"
)

func main()  {
    expression, err := govaluate.NewEvaluableExpression("first_name == 'Julian' && emp_id == 302 && birth_date >= '2016-12-12' && birth_date <= '2016-12-25'")

    parameters := make(map[string]interface{}, 8)
    parameters["first_name"] = "Julian"
    parameters["emp_id"] = 302
    parameters["birth_date"] = "2016-12-15"
    result, err := expression.Evaluate(parameters)

    if err != nil {
        fmt.Println("Error while evaluating the expression")
    }

    if result.(bool) {
        fmt.Println("Condition is evaluated to true")
    } else {
        fmt.Println("Condition is evaluated to false")
    }
}
```
I a getting this error:

```
Error while evaluating the expression
panic: interface conversion: interface is nil, not bool
```

I tried doing the following: convert the date literal into float and pass as a parameter.

```
dateFloat, _ := strconv.ParseFloat("2016-12-15", 64)
parameters["birth_date"] = dateFloat
```
Although, the error disappeared, the result value is false which is logically wrong since "2016-12-15" falls between "2016-12-12" and "2016-12-25".

Can you suggest me a way to achieve it?

**Comment by Knetic** [comment]
The library doesn't try to parse string parameters as dates - it expects that `birth_date` will be the [`Unix()`](https://golang.org/pkg/time/#Time.Unix) value of that date. This means you'll have to parse the date before passing it to govaluate.

If you're getting `birth_date` as part of a REST api, I'd suggest settling on one specific date format (such as ISO8601) and doing something like:

```
iso8601 := "2006-01-02T15:04:05Z0700"

birthDate, err := time.ParseInLocation(iso8601, birthDateString, time.Local)
parameters["birth_date"] = birthDate.Unix()
```

If you can't guarantee the format of the date, then you'll have to try a variety of date formats until you find one that works with the string you've got. govaluate has to do this for literal dates, and has an [internal function](https://github.com/Knetic/govaluate/blob/v3.0.0/parsing.go#L406) to try a variety of date formats when it parses literal dates, since it doesn't exactly know what format a date literal will be. You could do something pretty similar.

So while that will solve your issue, it's strange you saw a `panic` come from that - it should have given you a much more readable error - I try to keep it so that you never receive a panic from parsing or evaluation. I'll give it a look.

**Comment by VijayBhore** [comment]
It worked like charm. Thank you so much for timely response and awesome suggestions!  Really appreciate it.

**Comment by Knetic** [comment]
Ah, I just realized the reason you received a `panic` wasn't because of the library. When the library encounters an error during evaluation, it returns a `nil` result. So when you do this;

```
    result, err := expression.Evaluate(parameters) 
   // at this point, "result" is nil and "err" has a value.

    if err != nil {
        fmt.Println("Error while evaluating the expression") 
        // there's no "return" or anything here, so while this prints, the code just keeps going
    }

    // since result is nil, the next line will panic.
    if result.(bool) {
        fmt.Println("Condition is evaluated to true")
    }
```

**Comment by VijayBhore** [comment]
Yeah, i should have pointed it out. Thank You so much!
