### ISSUE TITLE
Hex literals cause panic

### ISSUE THREAD

**Issue by gautambt** [Knetic/govaluate#63]
The following code leads to a panic:

  expression, err := govaluate.NewEvaluableExpression("0x10 > 0");
  result, err := expression.Evaluate(nil);

Relavant stack trace
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x401753]

goroutine 1 [running]:
panic(0x5ef040, 0xc42000c0e0)
        /home/blah/blah/go-1.7.4/src/runtime/panic.go:500 +0x1a1

**Comment by Knetic** [comment]
That occurs because there was an error parsing the expression.

```
expression, err := govaluate.NewEvaluableExpression("0x10 > 0");
// "err" is non-nil, whereas "expression" is nil, since it could not be parsed.

result, err := expression.Evaluate(nil); // <- "expression" is nil, so it panics.
```

If you check the value of `err` after parsing, it'll tell you that it couldn't parse the hex literal - hex/octal literals are not supported, the library assumes all numerics are base 10. Offhand I don't think there's anything preventing hex literals from being supportable, just hasn't been done yet.

**Comment by gautambt** [comment]
You are right, adding the error check after NewEvaluableExpression removes the panic. This issue can be closed.
