### ISSUE TITLE
Can you help me slim down the library?

### ISSUE THREAD

**Issue by JPLennox** [Knetic/govaluate#67]
Thanks for this awesome library!
For a special use case I tried to slim it down to work only with float64 as parameters and results, and maybe boolean as interim results.
I want to get rid of the interfaces for performance reasons and wanted the result to be an error flag when one of the parameters is an error flag (>= 9.999.999).
I started by changing the parameters map to be a `map[string]float64` and then tried to hunt down the compiler errors.
But I have a hard time doing so.
May I ask for some hint?

Thanks in advance!

**Comment by Knetic** [comment]
Hey there! Thanks!

The library is pretty speedy right now. So the answer sorta depends on your performance targets - do you need faster expression parsing, or faster evaluation? How much faster do you need it to be? There's a few benchmarks written into the library right now, I'd probably recommend running them and getting a sense of how much more speed you need - is a 10% improvement good enough? Does it need to be more like 50%? etc.

That said, it's going to be nearly impossible to remove the `interface{}` use from the library, because the library was meant to work with multiple types right from the start - and it didn't have any type info built in besides what Go provides. Every operator and function call (as well as all the stage planning) use `interface{}` to represent values flowing through the library, so there's naturally going to be a certain amount of type assertions going on.

But there's a few things you can do.

Parameter customization
====

You can have your parameters be a map[string]float64 if you define a type that implements the 
[Parameters](https://github.com/Knetic/govaluate/blob/master/parameters.go) interface. So something like;

```
type FloatParameters map[string]float64

func (p FloatParameters) Get(name string) (interface{}, error) {

	value, found := p[name]

	if !found {
		errorMessage := "No parameter '" + name + "' found."
		return nil, errors.New(errorMessage)
	}

       // other error conditions here, like this:
       if value >= 9999999 {
               return nil, errors.New("parameter is an error flag")
       }

	return value, nil
}
```

You can give that an instance of that to `Evaluate`, and all parameters accessed will call that `Get` method. However, that won't speed anything up - just allow you to do more checking of the parameters (like how you mentioned some parameters are error flags) and ensure that only `float64` parameters get used. 

Speed
====

If you're looking for evaluation speed, there are three things I can suggest. 

1. Set [`ChecksTypes`](https://github.com/Knetic/govaluate/blob/93a54c2584a8b78856230ea1d31cfa2b61693721/EvaluableExpression.go#L33) to `false` after parsing your expression. This removes a lot of conditionals from the evaluation stage, but makes it so that your expression will panic if the types are not correct (as opposed to giving you an `error`). It speeds the process up by a decent margin, though. I haven't done benchmarks on it in a while, but i seem to recall about a 10% overhead going into the type checking.
If you wanted to get super-serious about it, you could even just fork the library and simply remove this [whole block](https://github.com/Knetic/govaluate/commit/93f778d2172335e459bd2fb6d8db5429ecedccdf#diff-1a1d4a8ca59572546ef316291432f40dR180) where it checks types. That'll save you a tiny bit more speed.

2. The next thing I'd probably suggest is forking the library and trimming out some of the overloaded functionality of the operators. Changing the `+`, `>`, `<`, `>=` and `<=` operator to not support strings would be a good start. Every time the library evaluates one of those, right now, it does some type checking to see if it ought to do [addition or concatenation](https://github.com/Knetic/govaluate/blob/93a54c2584a8b78856230ea1d31cfa2b61693721/evaluationStage.go#L89), or [lexicographic compare](https://github.com/Knetic/govaluate/blob/93a54c2584a8b78856230ea1d31cfa2b61693721/evaluationStage.go#L113). This wasn't always how the library worked, I added some of that support in https://github.com/Knetic/govaluate/commit/188c506adbcda72cfa0ad361291617bf793ccbf3 - you can see the diff to get an idea of what it looked like before (when the comparators only supported floats).<br/>
Those operators are currently slower than they used to be because they have to do a branch every time they're used - to check if they should work on numbers or strings. Branching is one of the slowest single things you can do in code (even if it's still pretty fast compared to the old days), so eliminating those would help you out a good deal.

3. Another thing you can do, if you're still alright with forking the library, is to change how equality is defined. Recently, I had to [switch to using `reflect.DeepEqual`](https://github.com/Knetic/govaluate/commit/8aa7234fb5802e12275ce6c92aa31a2323fbc9cf#diff-db719e95dbf8d99d460a74fe2d65285fL118) for really, really complicated reasons. But you could just as easily revert this change back to using the actual `==` Go operator, and that would speed things up a bit.

Those changes ought to get you some pretty decent performance gains, at the cost of panicking in more cases and losing a little bit of string functionality. But if you _really need speed_, that's what i can suggest.

**Comment by JPLennox** [comment]
Thank you very much for that fast and extensive answer. It helps me a lot.
I'm new in golang and also in github, but I will dig into it.

Some context:
My project is a data logger that collects values from various devices and shall also provide virtual channels. The user defined formulas don't get changed while the program is running (shall be 24/7), so parsing only happens once at the start of the program.
Some values may reflect an error, like
```
	Value_Underflow     float32  = 10000006
	Value_Overflow       float32 = 10000007
	Value_DeviceNotReady float32 = 10000011
```
I'd like to enhance this list with flags like `MissingParameter`, `NotANumber` or `DivisionByZero` when calculating arbitrary expressions. It would be nice to get such results directly from the Evaluate method instead of checking the returned error value.
Speed is not that much of an issue, although the code shall run on a Raspberry Pi and there may be a lot of virtual channels. Your hints will help optimizing for that.

In a next step I have to add most of the functions from the "math" library.
Do I have to define a long function map, or is there an easier way?

Last but not least  I want to apologise for my poor English.
Thanks a lot!

**Comment by Knetic** [comment]
No problem! And your English is great - I wish my German were half as good as your English! :]

If you haven't hit any performance bottlenecks yet, I'd probably wait on optimizing the library - Go itself is very fast, and this library isn't slow either. The optimizations i listed above should probably only be used if you're in dire need of performance improvements.

For the error flags, definitely use something like the code snippet i wrote in the previous comment (the `FloatParameters` thing). You can do your error flag checking there, it'll let you get errors back from `Evaluate` just like you want.

And, yeah, you'll have to define a really long function map. There's no "standard library" included with the expressions, it's up to you to define exactly what functions you need, and how they work. Every user of the library has slightly different needs, so it's best if everyone provide the functions they need on their own :]

**Comment by JPLennox** [comment]
Thank you very much!
